- name: Install charts
  block: 

  - name: Install required tools
    pip:
      executable: /usr/bin/pip3
      name: openshift
      state: present

  - name: Download CRD for Helm Operator
    get_url: 
      url: https://raw.githubusercontent.com/fluxcd/helm-operator/master/deploy/flux-helm-release-crd.yaml
      dest: /root/flux-helm-release-crd.yaml

  - name: Add CRDs for Helm Operator
    k8s:
      state: present
      src: /root/flux-helm-release-crd.yaml
    
  - name: Add Helm Operator
    helm_cli:
      name: helm-operator
      state: present
      release_namespace: fluxcd
      tiller_namespace: kube-system
      chart_repo_url: https://charts.fluxcd.io
      chart_ref: helm-operator
      values:
        image:
          repository: docker.io/huettner94/helm-operator
          tag: 1.0.0-rc3-arm64

  - name: Add fluxcd
    helm_cli:
      name: flux
      state: present
      release_namespace: fluxcd
      tiller_namespace: kube-system
      chart_repo_url: https://charts.fluxcd.io
      chart_ref: flux
      values:
        image:
          repository: docker.io/huettner94/flux
          tag: 1.15.0-arm64
        memcached:
          tag: "1.5.20"
        git:
          url: git@github.com:huettner94/k8s-flux.git

  when: k8s_root
