- name: Install MetalLB
  helm_cli:
    name: metallb
    state: present
    chart_ref: stable/metallb
    release_namespace: kube-system
    tiller_namespace: kube-system
    values:
      configInline:
        address-pools:
        - name: default
          protocol: layer2
          addresses:
          - 10.0.128.20-10.0.128.25
  when: k8s_root

- name: Install traefik
  helm_cli:
    name: traefik
    state: present
    chart_ref: stable/traefik
    release_namespace: kube-system
    tiller_namespace: kube-system
    values:
      rbac:
        enabled: true
      dashboard:
        enabled: true
        domain: traefik.apps.huettner.local
      ssl:
        enabled: true
        generateTLS: true
        defaultCN: apps.huettner.local
        defaultSANList:
          - "*.apps.huettner.local"
        insecureSkipVerify: true
  when: k8s_root

- name: Install rook operator
  helm_cli:
    name: rook
    state: present
    chart_repo_url: "https://charts.rook.io/release"
    chart_ref:  rook-ceph
    release_namespace: rook-ceph
    tiller_namespace: kube-system
  when: k8s_root

- name: Copy ceph-cluster chart
  copy:
    src: rook-cluster/
    dest: /opt/rook-cluster
  when: k8s_root

- name: Install ceph-cluster
  helm_cli:
    name: ceph-cluster
    state: present
    chart_ref: /opt/rook-cluster
    release_namespace: rook-ceph
    tiller_namespace: kube-system
    values:
      pools:
        replicated:
          - name: high
            replicas: 3
          - name: low
            replicas: 1
  when: k8s_root
