- hosts: all
  roles:
    - role: common
      tags: ["common"]
    - role: k8s
      tags: ["k8s"]
    - role: helm
      tags: ["helm"]
    - role: helm-clients
      tags: ["helm-clients"]
  become: true
